#!/usr/bin/env bash
# Regenerate the two indexes from each memory's frontmatter.
#
#   MEMORY.md          ALWAYS-ON  — injected into every context by inject-memory.sh
#   MEMORY-CATALOG.md  ON-DEMAND  — read by the recall command, never auto-injected
#
# Never hand-edit either file. Edit a memory's `name:` / `description:` frontmatter, or add a
# memory, and re-run. Context injected into every prompt is the scarcest resource here, which
# is the whole reason for the split: standing behavioural rules stay resident; project and
# reference memories are POINTERS, pulled in only when a topic arises.
#
#   bash engine/rebuild-index.sh            # operates on ${CLAUDE_CONFIG_DIR:-~/.claude}/memory
#   RAEMEMBERIT_MEMORY_DIR=/path bash ...        # or an explicit corpus
set -euo pipefail
. "$(dirname "$0")/lib/raememberit-root.sh"
cd "$RAEMEMBERIT_MEM" || { echo "rebuild-index: no corpus at $RAEMEMBERIT_MEM" >&2; exit 1; }

RECENT_N="${RAEMEMBERIT_RECENT_N:-8}"   # how many latest interaction logs to surface

get_name() { awk 'NR<=6 && /^name:/{sub(/^name:[ ]*/,""); gsub(/^"|"$/,""); print; exit}' "$1"; }
get_desc() {
  local d
  d=$(awk 'NR<=15 && /^description:/{sub(/^description:[ ]*/,""); gsub(/^"|"$/,""); print; exit}' "$1")
  [ -n "$d" ] && { echo "$d"; return; }
  awk '/^---[ ]*$/{fm++; next} fm==1{next} /^#/{sub(/^#+[ ]*/,""); print; exit} NF{print; exit}' "$1"
}
# A non-matching glob makes `ls` exit non-zero, and under `set -o pipefail` that aborts the
# whole generation — which is precisely the EMPTY-CORPUS case, i.e. every fresh install. The
# SessionEnd hook wraps this script in `|| true`, so such a failure is completely silent: a
# truncated MEMORY.md and no catalog at all, with no error anywhere. `find` succeeds on an
# empty directory, so it is used for every listing and count below.
list_md()  { find "$1" -maxdepth 1 -name '*.md' 2>/dev/null; }
count_md() { list_md "$1" | wc -l | tr -d ' '; }
emit() {  # $1 = section title, $2 = dir
  printf '\n## %s\n' "$1"
  for f in "$2"/*.md; do
    [ -e "$f" ] || continue
    local nm; nm=$(get_name "$f"); [ -z "$nm" ] && nm=$(basename "$f" .md)
    printf -- '- [%s](%s) — %s\n' "$nm" "$f" "$(get_desc "$f")"
  done
}

# ---- ALWAYS-ON ----------------------------------------------------------------------
{
  echo "# Memory Index"
  echo "<!-- AUTO-GENERATED by engine/rebuild-index.sh — do not hand-edit; edit frontmatter and re-run. -->"
  echo ""
  [ -f user_profile.md ] && printf -- '- [user-profile](user_profile.md) — %s\n' "$(get_desc user_profile.md)"
  emit "Feedback" feedback
  printf '\n## Recent work (latest %s interaction logs)\n' "$RECENT_N"
  list_md interactions | sort -r | head -"$RECENT_N" | while read -r f; do
    printf -- '- [%s](%s) — %s\n' "$(basename "$f" .md)" "$f" "$(get_desc "$f")"
  done
  printf '\n## On-demand catalog — NOT loaded here\n'
  printf -- '%s project + %s reference memories are indexed in `MEMORY-CATALOG.md`.\n' \
    "$(count_md project)" "$(count_md reference)"
  printf 'When a task touches a repo, ticket, tool or environment not already in context, search\n'
  printf 'that catalog BEFORE investigating from scratch. Assume a relevant memory exists until\n'
  printf 'the catalog says otherwise.\n'
} > MEMORY.md

# ---- ON-DEMAND ---------------------------------------------------------------------
{
  echo "# Memory Catalog (on-demand)"
  echo "<!-- AUTO-GENERATED by engine/rebuild-index.sh. Read on demand, NOT injected per prompt. -->"
  emit "Project"   project
  emit "Reference" reference
  printf '\n## All interaction logs\n'
  printf 'Full session history lives in `interactions/` (%s files), named\n' \
    "$(count_md interactions)"
  printf '`YYYY-MM-DD-HH-MM-topic.md`. Grep the directory by topic keyword.\n'
} > MEMORY-CATALOG.md

echo "MEMORY.md:         $(grep -c '^- \[' MEMORY.md || true) entries, $(wc -c < MEMORY.md | tr -d ' ') bytes (always-on)"
echo "MEMORY-CATALOG.md: $(grep -c '^- \[' MEMORY-CATALOG.md || true) entries, $(wc -c < MEMORY-CATALOG.md | tr -d ' ') bytes (on-demand)"
