#!/usr/bin/env bash
# SessionStart — detect that the memory injection was TRUNCATED, from evidence rather than prediction.
#
# WHY THIS EXISTS: inject-memory.sh emits MEMORY.md as UserPromptSubmit additionalContext. Above an
# undocumented size ceiling the harness does not inject it — it writes the payload to
# <config>/projects/<proj>/<session>/tool-results/hook-*-additionalContext.txt and passes the model a
# ~2KB preview plus a file path. Nothing errors. The hook exits 0. Measured 2026-09-28: 13
# consecutive sessions delivered 8 of 71 index entries this way, starting 2026-09-27 18:07.
#
# WHY NOT A SIZE GUARD: the ceiling is undocumented, was observed only from below (smallest payload
# seen persisted: 15,493 B; the largest that got through was never observed), and lives in a
# self-updating binary. A hardcoded budget encodes a GUESS about a proxy. This checks the actual
# property — did the payload arrive — by looking for the artifact the harness itself writes when it
# did not. Threshold-independent, and it survives the ceiling moving in either direction.
#
# COST: measured 0.01s over 136 inodes / 33MB against a 5s timeout.
# TRADE-OFF: detects one session late. It cannot prevent; it can only stop the silence.
#
#   $RAEMEMBERIT_TRIPWIRE = off        disable entirely
#   $RAEMEMBERIT_TRIPWIRE_WINDOW_H     how far back to look, in hours (default 48)
#
# The window is also the reset: once the payload fits again no new artifacts are written, and the
# warning ages out by itself. No marker file, nothing to forget to clear.
set -uo pipefail
. "$(dirname "$0")/../lib/raememberit-root.sh"
[ "${RAEMEMBERIT_TRIPWIRE:-on}" = off ] && exit 0

PROJ="$RAEMEMBERIT_CONFIG/projects"
[ -d "$PROJ" ] || exit 0
H="${RAEMEMBERIT_TRIPWIRE_WINDOW_H:-48}"
IDX="$RAEMEMBERIT_MEM/MEMORY.md"

# ATTRIBUTION. The artifact is written for ANY oversized UserPromptSubmit additionalContext, not
# only this one. An install may well have no other such hook, but that is a fact about one config,
# not an invariant — so confirm the payload is ours before blaming it. This marker is emitted by
# rebuild-index.sh into MEMORY.md's second line and has no other source.
# Matched loosely ON PURPOSE: the banner wording has already changed once across versions
# (`by rebuild-index.sh` -> `by engine/rebuild-index.sh`), and an exact match silently skipped the
# oldest artifact — a tripwire that under-reports is the failure it was built to catch.
MARK='AUTO-GENERATED by .*rebuild-index\.sh'

HITS=0; NEWEST=0
while IFS= read -r f; do
  grep -qE "$MARK" "$f" 2>/dev/null || continue
  HITS=$((HITS+1))
  s=$(wc -c < "$f" 2>/dev/null | tr -d ' '); [ "${s:-0}" -gt "$NEWEST" ] && NEWEST=$s
done < <(find "$PROJ" -name 'hook-*-additionalContext.txt' -mmin "-$((H*60))" 2>/dev/null | head -50)

# The over-budget verdict from rebuild-index.sh surfaces HERE. That script runs from a SessionEnd
# hook whose output is redirected to a log, so its exit code reaches no one; this is the first
# moment afterwards that anything is actually shown to a human.
STATUS=""
read -r ST SZ BG < "$RAEMEMBERIT_MEM/.index-status" 2>/dev/null || ST=""
[ "${ST:-}" = OVER ] && STATUS=" The last rebuild also flagged it OVER BUDGET (${SZ} B > ${BG} B)."

[ "$HITS" -eq 0 ] && { [ -n "$STATUS" ] && jq -n --arg s "$STATUS" '{"systemMessage":("raememberit:" + $s)}'; exit 0; }

CUR=$(wc -c < "$IDX" 2>/dev/null | tr -d ' '); CUR="${CUR:-?}"

# THE PRESCRIPTION MUST TRACK THE CURRENT STATE, NOT THE EVIDENCE. The artifacts are historical by
# construction — the window looks BACK. Once the index has been trimmed, telling the reader to
# "shrink the always-on tier" is advice about a problem they already solved, and a tripwire that
# cries about a fixed fault is one a reasonable person learns to ignore. So the verdict from the
# last rebuild, not the artifact count, decides what this asks for.
if [ "${ST:-}" = OVER ]; then
  ADVICE="Standing rules are not reaching the model; demote feedback memories with \`metadata.scope: domain\`.${STATUS}"
else
  ADVICE="The index has since been reduced to ${CUR} B and the last rebuild passed its budget, so this is historical — it clears itself once those sessions age past ${H}h."
fi

jq -n --arg n "$HITS" --arg h "$H" --arg b "$NEWEST" --arg i "$IDX" --arg a "$ADVICE" \
  '{"systemMessage":("raememberit: the memory index was NOT injected in \($n) session(s) in the last \($h)h — the harness truncated it to a file preview (largest payload \($b) B). \($a)")}'
exit 0
