#!/usr/bin/env python3
"""Generate a hooks-only plugin from the settings fragment.

Used by `install.sh --hooks-from-plugin`. The arrangement it serves: the ENGINE stays in the config
directory and only the HOOKS come from a plugin. That is the shape an adopted setup ends up in, because
hand-edited commands hardcode the config-dir engine paths and moving the engine breaks them silently.

The fragment's hook commands are already `${CLAUDE_CONFIG_DIR:-$HOME/.claude}/raememberit/engine/hooks/…`,
which is exactly where this mode leaves the engine — so they are copied VERBATIM. Nothing is transformed,
so nothing can be transformed wrongly.

Kept as a file rather than inlined in install.sh for one plain reason: it is a Python heredoc inside a
shell script that is itself often edited through heredocs, and nested same-delimiter heredocs silently
truncate. That cost a mangled script once already.
"""
import json, pathlib
import os
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: gen-hooks-only-plugin.py <settings.fragment.json> <skill-dir>", file=sys.stderr)
        return 2
    frag_path, skilldir = sys.argv[1], sys.argv[2]
    frag = json.load(open(frag_path))
    hooks = frag.get("hooks") or {}
    if not hooks:
        # An empty fragment would produce a plugin that silently does nothing — the failure this project
        # keeps meeting. Refuse instead.
        print("  refusing to generate a plugin with no hooks in it", file=sys.stderr)
        return 1

    # ONE SOURCE — see VERSION at the repo root. This file previously carried its own literal, and
    # since it is the generator the INSTALLER uses, a bump elsewhere never reached a real install.
    version = (pathlib.Path(__file__).resolve().parent.parent / "VERSION").read_text().strip()

    manifest = {
        "name": "raememberit",
        "version": version,
        "description": (
            "raememberit's hooks only. The engine lives in the config directory at raememberit/engine, "
            "which is where these commands resolve to, so anything else referencing that path keeps "
            "working. Generated by install.sh --hooks-from-plugin."
        ),
        "author": {"name": "raememberit"},
        # Deliberately no userConfig: configuration in this arrangement comes from settings `env`, which
        # the options bridge ranks above any option, so a declared option would be silently shadowed.
    }
    hooks_doc = {
        "description": (
            "GENERATED by install.sh --hooks-from-plugin from engine/settings.fragment.json. Commands are "
            "config-dir relative ON PURPOSE: the engine is not inside this plugin. Do not hand-edit; "
            "re-run the installer."
        ),
        "hooks": hooks,
    }

    os.makedirs(os.path.join(skilldir, ".claude-plugin"), exist_ok=True)
    os.makedirs(os.path.join(skilldir, "hooks"), exist_ok=True)
    for rel, doc in ((os.path.join(".claude-plugin", "plugin.json"), manifest),
                     (os.path.join("hooks", "hooks.json"), hooks_doc)):
        path = os.path.join(skilldir, rel)
        with open(path, "w") as f:
            json.dump(doc, f, indent=2)
            f.write("\n")

    n = sum(len(g["hooks"]) for groups in hooks.values() for g in groups)
    print(f"  \033[1;32m✓\033[0m generated a hooks-only plugin at {skilldir} — {n} hook(s), "
          f"resolving to the config-dir engine")
    return 0


if __name__ == "__main__":
    sys.exit(main())
