#!/usr/bin/env bash
# The delivery path: tiering, the always-on budget, and the truncation tripwire.
#
#     tools/test-tripwire.sh
#
# WHY THIS SUITE EXISTS. Above an undocumented size ceiling the harness does not inject a
# UserPromptSubmit hook's additionalContext — it writes the payload to a file, hands the model a
# short preview and a path, and reports no error. An always-on index that grew past that ceiling
# therefore stopped being delivered while every existing assertion stayed green: measured on a real
# corpus, 13 consecutive sessions received 8 of 71 index entries and nothing anywhere said so.
#
# Everything below asserts the machinery built for that. It is deliberately hostile about the two
# ways such machinery fails quietly: an alarm that under-reports, and an alarm that keeps firing
# about a fault already fixed. Both are indistinguishable from working, from the inside.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Knobs an adopted setup may set reach a running session's environment; a suite that inherits them
# is not testing the shipped defaults.
unset RAEMEMBERIT_MEMORY_DIR RAEMEMBERIT_TRIPWIRE RAEMEMBERIT_TRIPWIRE_WINDOW_H \
      RAEMEMBERIT_ALWAYS_ON_BUDGET RAEMEMBERIT_RECENT_N RAEMEMBERIT_DUPES 2>/dev/null || true
W="${TMPDIR:-/tmp}/raememberit-tripwire.$$"; mkdir -p "$W"
trap 'rm -rf "$W"' EXIT

pass=0; fail=0
ok()  { printf '  ok    %s\n' "$1"; pass=$((pass+1)); }
bad() { printf '  FAIL  %s\n' "$1"; [ $# -gt 1 ] && printf '        %s\n' "$2"; fail=$((fail+1)); }

TRIP="$ROOT/engine/hooks/truncation-tripwire.sh"
REBUILD="$ROOT/engine/rebuild-index.sh"
MEMW="$ROOT/engine/mem-write.sh"

# ---- fixtures -----------------------------------------------------------------------------
# $1 = corpus dir, $2 = how many feedback memories, $3 = scope line or empty
seed() {
  local mem="$1" n="$2" scope="${3:-}" i
  mkdir -p "$mem/feedback" "$mem/project" "$mem/reference" "$mem/interactions"
  for i in $(seq 1 "$n"); do
    { printf -- '---\nname: rule-%s\ndescription: seeded rule %s covering topic %s, worded distinctly so the duplicate gate has nothing to score\nmetadata:\n  type: feedback\n' "$i" "$i" "$i"
      [ -n "$scope" ] && printf '  scope: %s\n' "$scope"
      printf -- '---\n\nbody\n\n**Why:** seeded\n**How to apply:** seeded\n'
    } > "$mem/feedback/rule-$i.md"
  done
}
# $1 = config dir, $2 = filename stem, $3 = marker text to embed (empty = no marker)
artifact() {
  local cfg="$1" stem="$2" mark="${3:-}" d="$1/projects/proj/$2/tool-results"
  mkdir -p "$d"
  { [ -n "$mark" ] && printf '# Memory Index\n<!-- %s -->\n' "$mark"; printf 'payload\n'; } \
    > "$d/hook-$stem-additionalContext.txt"
  printf '%s\n' "$d/hook-$stem-additionalContext.txt"
}

echo "=== the tripwire reports a truncation, and only a real one ==="
CFG="$W/c1"; MEM="$CFG/memory"; seed "$MEM" 2
RAEMEMBERIT_MEMORY_DIR="$MEM" bash "$REBUILD" >/dev/null 2>&1

out=$(CLAUDE_CONFIG_DIR="$CFG" RAEMEMBERIT_MEMORY_DIR="$MEM" bash "$TRIP" </dev/null)
[ -z "$out" ] && ok "silent when no session was ever truncated" \
               || bad "fired with no artifacts present" "$out"

artifact "$CFG" sess1 'AUTO-GENERATED by engine/rebuild-index.sh' >/dev/null
out=$(CLAUDE_CONFIG_DIR="$CFG" RAEMEMBERIT_MEMORY_DIR="$MEM" bash "$TRIP" </dev/null)
printf '%s' "$out" | grep -q 'NOT injected in 1 session' \
  && ok "reports one truncated session" || bad "did not report the artifact" "$out"

# ATTRIBUTION. The harness writes this artifact for ANY oversized UserPromptSubmit hook, not only
# this one. Blaming another hook's payload would send someone trimming a corpus that was never big.
artifact "$CFG" sess2 '' >/dev/null
out=$(CLAUDE_CONFIG_DIR="$CFG" RAEMEMBERIT_MEMORY_DIR="$MEM" bash "$TRIP" </dev/null)
printf '%s' "$out" | grep -q 'in 1 session' \
  && ok "ignores an artifact that is not this hook's payload" || bad "counted a foreign artifact" "$out"

# The banner wording has already changed once across versions. An exact-match attribution silently
# skipped the oldest artifact when this was first written — an alarm that under-reports is the
# failure it exists to catch, so both spellings must count.
artifact "$CFG" sess3 'AUTO-GENERATED by rebuild-index.sh' >/dev/null
out=$(CLAUDE_CONFIG_DIR="$CFG" RAEMEMBERIT_MEMORY_DIR="$MEM" bash "$TRIP" </dev/null)
printf '%s' "$out" | grep -q 'in 2 session' \
  && ok "matches the pre-rename banner wording too" || bad "missed the older banner spelling" "$out"

echo "=== the window is also the reset ==="
touch -t 200001010000 "$CFG/projects/proj/sess1/tool-results/hook-sess1-additionalContext.txt"
touch -t 200001010000 "$CFG/projects/proj/sess3/tool-results/hook-sess3-additionalContext.txt"
out=$(CLAUDE_CONFIG_DIR="$CFG" RAEMEMBERIT_MEMORY_DIR="$MEM" bash "$TRIP" </dev/null)
[ -z "$out" ] && ok "an aged-out truncation clears itself with no marker file" \
               || bad "still reporting artifacts older than the window" "$out"

echo "=== the off switch, and never blocking a session ==="
artifact "$CFG" sess4 'AUTO-GENERATED by engine/rebuild-index.sh' >/dev/null
out=$(CLAUDE_CONFIG_DIR="$CFG" RAEMEMBERIT_MEMORY_DIR="$MEM" RAEMEMBERIT_TRIPWIRE=off bash "$TRIP" </dev/null)
[ -z "$out" ] && ok "RAEMEMBERIT_TRIPWIRE=off silences it" || bad "off switch ignored" "$out"
CLAUDE_CONFIG_DIR="$CFG" RAEMEMBERIT_MEMORY_DIR="$MEM" bash "$TRIP" </dev/null >/dev/null 2>&1
[ $? -eq 0 ] && ok "exits 0 even while reporting — a SessionStart hook must not block" \
              || bad "non-zero exit would interfere with session start"

echo "=== the advice tracks the present, not the evidence ==="
# The artifacts are historical by construction: the window looks BACK. Once the index has been
# trimmed, telling the reader to shrink it is advice about a problem they already solved — and an
# alarm that cries about a fixed fault is one a reasonable person learns to ignore.
printf 'OK 5000 12000\n' > "$MEM/.index-status"
out=$(CLAUDE_CONFIG_DIR="$CFG" RAEMEMBERIT_MEMORY_DIR="$MEM" bash "$TRIP" </dev/null)
printf '%s' "$out" | grep -q 'historical' \
  && ok "a healthy index makes the warning read as historical" || bad "still prescribing a fix" "$out"
printf '%s' "$out" | grep -qi 'demote' \
  && bad "prescribes demotion although the index is already under budget" "$out" \
  || ok "does not prescribe a trim that is already done"

printf 'OVER 18666 12000\n' > "$MEM/.index-status"
out=$(CLAUDE_CONFIG_DIR="$CFG" RAEMEMBERIT_MEMORY_DIR="$MEM" bash "$TRIP" </dev/null)
printf '%s' "$out" | grep -q 'scope: domain' \
  && ok "an over-budget index gets the actionable prescription" || bad "no actionable advice" "$out"

echo "=== the budget gate installs the index either way ==="
CFG2="$W/c2"; MEM2="$CFG2/memory"; seed "$MEM2" 40
RAEMEMBERIT_MEMORY_DIR="$MEM2" RAEMEMBERIT_ALWAYS_ON_BUDGET=500 bash "$REBUILD" >/dev/null 2>&1
rc=$?
[ "$rc" -ne 0 ] && ok "over budget is a non-zero verdict" || bad "over-budget rebuild reported success"
grep -q '^OVER ' "$MEM2/.index-status" && ok "the verdict lands in .index-status" \
                                       || bad ".index-status does not record OVER"
# A stale or missing index is worse than a large one, and `{ ... } > MEMORY.md` truncates the file
# the moment it opens — so a failure part-way through generation used to leave a half-written index
# with no error. Staging and mv is what makes this assertion possible.
seeded=$(find "$MEM2/feedback" -name '*.md' | wc -l | tr -d ' ')
[ "$(grep -c '^- \[' "$MEM2/MEMORY.md")" -eq "$seeded" ] \
  && ok "the index is still installed and complete when over budget" \
  || bad "over-budget rebuild left an incomplete index" "$(grep -c '^- \[' "$MEM2/MEMORY.md") entries"

RAEMEMBERIT_MEMORY_DIR="$MEM2" RAEMEMBERIT_ALWAYS_ON_BUDGET=999999 bash "$REBUILD" >/dev/null 2>&1 \
  && ok "under budget exits clean" || bad "under-budget rebuild reported failure"
grep -q '^OK ' "$MEM2/.index-status" && ok "a passing rebuild records OK" || bad "no OK verdict"

echo "=== tiering routes by scope, and absence is the safe default ==="
CFG3="$W/c3"; MEM3="$CFG3/memory"; seed "$MEM3" 3            # no scope line at all
RAEMEMBERIT_MEMORY_DIR="$MEM3" bash "$REBUILD" >/dev/null 2>&1
[ "$(grep -c '(feedback/' "$MEM3/MEMORY.md")" -eq 3 ] \
  && ok "an unlabelled feedback memory defaults to the always-on tier" \
  || bad "absent scope did not default to global — an older corpus would go dark on upgrade"

seed "$MEM3" 3 domain
RAEMEMBERIT_MEMORY_DIR="$MEM3" bash "$REBUILD" >/dev/null 2>&1
[ "$(grep -c '(feedback/' "$MEM3/MEMORY.md")" -eq 0 ] \
  && ok "scope: domain leaves the always-on tier" || bad "a domain rule stayed always-on"
[ "$(grep -c '(feedback/' "$MEM3/MEMORY-CATALOG.md")" -eq 3 ] \
  && ok "and arrives in the on-demand catalog — demoted, never dropped" \
  || bad "a demoted rule vanished from both indexes"

seed "$MEM3" 3 global
RAEMEMBERIT_MEMORY_DIR="$MEM3" bash "$REBUILD" >/dev/null 2>&1
[ "$(grep -c '(feedback/' "$MEM3/MEMORY.md")" -eq 3 ] \
  && ok "scope: global is always-on" || bad "an explicit global rule did not stay always-on"

echo "=== the helper enforces the field, and does not confuse a verdict with a failure ==="
CFG4="$W/c4"; MEM4="$CFG4/memory"; seed "$MEM4" 1
printf -- '---\nname: p1\ndescription: rejects a scope value that is neither of the two the generator understands\nmetadata:\n  type: feedback\n  scope: banana\n---\n\nbody\n\n**Why:** p\n**How to apply:** p\n' \
  | RAEMEMBERIT_MEMORY_DIR="$MEM4" bash "$MEMW" feedback p1 >/dev/null 2>&1
[ $? -ne 0 ] && ok "an invalid scope is refused" || bad "accepted a scope value that is neither global nor domain"

printf -- '---\nname: p2\ndescription: accepts a well formed domain tier declaration on a feedback memory\nmetadata:\n  type: feedback\n  scope: domain\n---\n\nbody\n\n**Why:** p\n**How to apply:** p\n' \
  | RAEMEMBERIT_MEMORY_DIR="$MEM4" bash "$MEMW" feedback p2 >/dev/null 2>&1
[ $? -eq 0 ] && ok "a valid scope is accepted" || bad "refused a well-formed scope"

# The rebuild runs at the end of every write and exits non-zero when the CORPUS is over budget.
# That is a verdict about the corpus, not about this write, which already succeeded — propagating it
# would make every future write report failure on a perfectly good memory until the tier is trimmed.
printf -- '---\nname: p3\ndescription: proves a corpus wide byte verdict is not reported as this single write failing\nmetadata:\n  type: feedback\n  scope: global\n---\n\nbody\n\n**Why:** p\n**How to apply:** p\n' \
  | RAEMEMBERIT_MEMORY_DIR="$MEM4" RAEMEMBERIT_ALWAYS_ON_BUDGET=1 bash "$MEMW" feedback p3 >/dev/null 2>&1
[ $? -eq 0 ] && ok "a successful write exits 0 even while the corpus is over budget" \
              || bad "a corpus verdict was propagated as a write failure"
[ -f "$MEM4/feedback/p3.md" ] && ok "and the memory really was written" || bad "the write did not land"

echo "=== the eval asserts delivery, not only retrieval ==="
# It reads the corpus off disk, so it stayed green through every truncated session. A retrieval
# score describes a corpus the model may never have received; the delivery verdict has to come first.
j=$(RAEMEMBERIT_MEMORY_DIR="$MEM3" CLAUDE_CONFIG_DIR="$CFG3" python3 "$ROOT/engine/eval/run_eval.py" --health --json 2>/dev/null)
printf '%s' "$j" | python3 -c 'import json,sys; d=json.load(sys.stdin); sys.exit(0 if "delivery" in d else 1)' 2>/dev/null \
  && ok "--json carries a delivery verdict" || bad "the eval reports no delivery verdict"
printf '%s' "$j" | python3 -c 'import json,sys; d=json.load(sys.stdin)["delivery"]; sys.exit(0 if d["delivered"] is True else 1)' 2>/dev/null \
  && ok "a corpus with no truncated sessions reports delivered" || bad "clean corpus reported as undelivered"

printf '\n%s passed, %s failed\n' "$pass" "$fail"
[ "$fail" -eq 0 ]
